# Generated by Django 3.0.3 on 2020-05-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200510_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
